### PR TITLE
Separate styles in css bundle

### PR DESCRIPTION
**Pull request by juanarbol**
Using webpack `extract-text-webpack-plugin` for extract .css and .styl files and the app module.

### CODE REVIEW

**Comment by juanarbol** [comment]
anything wrong? :/

**Comment by christian-fei** [comment]
Hello,
sorry for the delay..
Will merge it instantly!
Thank you for the reminder :)

**Comment by juanarbol** [comment]
If U want, you can mention me in other issue, this project is great!

**Comment by christian-fei** [comment]
@juanarbol That would soooo awesome!
I will create some issue with ideas of improvements and sort of a roadmap.
The project [`💥✨pomodoro.cc 🔥⚡️`](https://github.com/christian-fei/pomodoro.cc/projects/1) represents the current picture of what is in plan for the future and what is currently being worked on.
Let's have a discussion on some issues, feel free to ping me, let me know :)

**Pull request merged**
